test compile precise-output
target a32

function %eq32(f32, f32) -> i8 {
block0(v0: f32, v1: f32):
    v2 = fcmp eq v0, v1
    return v2
}

; block0:
;   call %CmpF32
;   bit a0, 2
;   mv.neq a0, zero, 1
;   ret


function %eq64(f64, f64) -> i8 {
block0(v0: f64, v1: f64):
    v2 = fcmp eq v0, v1
    return v2
}

; block0:
;   call %CmpF64
;   bit a0, 2
;   mv.neq a0, zero, 1
;   ret


function %eq_brif(f32, f32) -> i32 {
block0(v0: f32, v1: f32):
  v2 = fcmp eq v0, v1
  brif v2, block1, block2

block1:
  v3 = iconst.i32 1
  return v3

block2:
  v4 = iconst.i32 2
  return v4
}

; block0:
;   call %CmpF32
;   bit a0, 2
;   br.neq MachLabel(1), MachLabel(2)
; block1:
;   ldi a0, 1
;   ret
; block2:
;   ldi a0, 2
;   ret
